// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvDo5Effme4t1kabDkyfEEGixNj5rUh6M',
    appId: '1:920430939888:web:fb2ae7023352309587fc35',
    messagingSenderId: '920430939888',
    projectId: 'heartcloud-c5817',
    authDomain: 'heartcloud-c5817.firebaseapp.com',
    storageBucket: 'heartcloud-c5817.firebasestorage.app',
    measurementId: 'G-VDDPNKE1G9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALx99icKBWmstPrzKiU0NUOEgHhSCS4P0',
    appId: '1:920430939888:android:bf9c36a9908c7e3787fc35',
    messagingSenderId: '920430939888',
    projectId: 'heartcloud-c5817',
    storageBucket: 'heartcloud-c5817.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMcDa1iO5I0tvar8S8Zrv_mCayIgPFxtw',
    appId: '1:920430939888:ios:b42f052b7e6eefdf87fc35',
    messagingSenderId: '920430939888',
    projectId: 'heartcloud-c5817',
    storageBucket: 'heartcloud-c5817.firebasestorage.app',
    iosBundleId: 'com.example.heartcloud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMcDa1iO5I0tvar8S8Zrv_mCayIgPFxtw',
    appId: '1:920430939888:ios:b42f052b7e6eefdf87fc35',
    messagingSenderId: '920430939888',
    projectId: 'heartcloud-c5817',
    storageBucket: 'heartcloud-c5817.firebasestorage.app',
    iosBundleId: 'com.example.heartcloud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvDo5Effme4t1kabDkyfEEGixNj5rUh6M',
    appId: '1:920430939888:web:9cdc8c3385ff5f8087fc35',
    messagingSenderId: '920430939888',
    projectId: 'heartcloud-c5817',
    authDomain: 'heartcloud-c5817.firebaseapp.com',
    storageBucket: 'heartcloud-c5817.firebasestorage.app',
    measurementId: 'G-DP24JTLB0R',
  );
}
